"""Add collected_by, status, company_info to Upload

Revision ID: c4e0a96888d0
Revises: 90825d806e05
Create Date: 2025-11-04 00:50:29.056251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e0a96888d0'
down_revision = '90825d806e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collected_by', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_info', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company_info')

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('company_info')
        batch_op.drop_column('status')
        batch_op.drop_column('collected_by')

    # ### end Alembic commands ###
